### ISSUE TITLE
View and Assess Team Activity

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/use-case-library-build#17]
So. I think a really useful thing for people on our team (@nih-cfde/training) to do, is to get more comfortable with use cases. 

That will help both with this ["what needs to be in the docs" questions](https://github.com/nih-cfde/use-case-library-build/pull/13), as well as just generally it would be great if everyone understands use cases going forward. For instance, this issue template is for people to give us the bare pieces of a use case, so we can build it for them. I need everyone to be able to do that. So, I'm going to fill in the rest of this with the type of information someone would submit, for a real use case I need added anyway. Please take a shot at building it. When building, be sure to consult https://github.com/nih-cfde/use-case-library-build/pull/12 as @jeremywalter is assigning IDs to files.

- [x] A descriptive title
- [x] Details about the required use case components: use case, persona, objective, user tasks, and requirements

This is a use case for the CFDE portal. The use case is that someone with admin rights for a DCC should be able to get into the portal and see what data submissions their team has done, to look at summaries of those data submissions, and to notify the person on their team who makes the final decision which one should get incorporated into the portal that it's time to come do the final review.

I've included the unique user tasks below. 

A data administrator or data custodian should be able to:

- See a display showing their team’s data submission activity including
    - a list of recent submissions by their own team members
    - relevant diagnostics for each ingest: errors, warnings, summaries
- Navigate to any Review catalog belonging to their own team(s)
- Compare any different available Review Catalogs belonging to their own team(s)
- Reject/delete any available Review Catalogs belonging to their own team(s)
- Notify their teams Data administrator that there are Review Catalogs slated for Review

**Comment by marisalim** [comment]
### --- DRAFT ---

**Note: all the new uc, t, r files have to be re-numbered. new ucs have been added since this was drafted**

I think objective 4 [(obj-0004-single-dcc-release.md)](https://github.com/nih-cfde/use-case-library-build/blob/contentmove/library/obj-0004-single-dcc-release.md) task 1 [(t-0001-access-cfde-interface.md)](https://github.com/nih-cfde/use-case-library-build/blob/contentmove/library/t-0001-access-cfde-interface.md), and requirement 29 [(r-00029-the-interface-allows-data-administrators-to-review-the-ingest-results.md)](https://github.com/nih-cfde/use-case-library-build/blob/contentmove/library/r-00029-the-interface-allows-data-administrators-to-review-the-ingest-results.md) might apply for this use case. Also, personas for data admin and data custodian.

Until they are in the repo (they will when #12 is merged), the website is not going to build. Also, because I need help figuring out the requirements for each task! @nih-cfde/training 

So, below is a draft of the new submission files for this use case. Here is the list of all existing use case library files: https://github.com/nih-cfde/use-case-library-build/tree/contentmove/library

#### use case file
- uc-0008-check-cfde-portal-submissions.md
```
---
title: Check CFDE Portal Submissions
persona:
- p-003
- p-004
objective:
- obj-0004 <- this might fit? 
user_tasks:
- t-0001 <- this seems right
- t-0020
- t-0021
- t-0022
- t-0023
- t-0024
requirements:
- r-00029
- r-00034
- r-00035
---

Melinda wants to check her team's data submissions on the CFDE portal so they can review which are ready to incorporate into the portal.

She logs on to the portal interface and looks at summaries of their data submissions. Next she notifies Ann, the person on her team who makes the final decision, that it is time to do a final review of the data.
```

#### user task files
- t-0020-see-data-submission-activity.md
```
---
title: See team data submission activity
requirements:
- r-00029 <--i think this fits
- r-00034
- r-00035
---
```

- t-0021-navigate-to-team-review-catalogs.md
```
---
title: Navigate to team Review Catalogs
requirements:
- ???
---
```

- t-0022-compare-different-available-team-review-catalogs.md
```
---
title: Compare different available team Review Catalogs
requirements:
- ???
---
```

- t-0023-reject-or-delete-available-team-review-catalogs.md
```
---
title: Reject/delete available team Review Catalog
requirements:
- ???
---
```

- t-0024-notify-team-data-admin-there-are-review-catalogs-to-review.md
```
---
title: Notify team data administrator there are Review Catalogs to review
requirements:
- ???
---
```

#### requirements files
- r-00034-the-interface-will-show-recent-submissions
```
---
title: The interface will show recent submissions
---
```

- r-00035-the-cfde-ingest-tool-shows-errors-warnings-summaries.md
```
---
title: The cfde ingest tool shows errors/warnings/summaries
---
```

**Comment by ACharbonneau** [comment]
This is a really good start. And while we might change the specific tasks/requirements as we go, you're doing the *process* exactly right :)

Couple points I want to make:

- hopefully working through this will help you think about https://github.com/nih-cfde/use-case-library-build/pull/13#issuecomment-722424943 You are *specifying* all these pieces, but you didn't, for instance, make up a new persona. And that's good. Can you make the contributing docs reflect this process a bit better? 

- Requirements are the technical implementation bits for what needs to happen. For this use case, and in general, our team *won't* be conjuring up new requirements. We're not the technical implementation team. So it's fine to get to this point and then ask for help from the tech team. We'll work out how to actually do that later, right now it's just I ask at our weekly meeting.

**Comment by ACharbonneau** [comment]
Hey @lliming do you have any suggestions about requirements for this use case? Or who I should ask for them?

**Comment by marisalim** [comment]
does this use case require authenticated access to the CFDE in order to check team submissions? (if so i need to switch to task 17 instead of task 1)

**Comment by ACharbonneau** [comment]
yes this requires authentication
